### ISSUE TITLE
Requests are broken when users have uppercase letters in their name

### ISSUE THREAD

**Issue by bfleyshe** [CMPUT301W17T12/ProjectAttitude#147]
Boris sends a request to Chris. Boris can send another request to Chris repeatedly, which is not working as intended.
Chris receives the request, and accepts it. When he visits his requests again, the request is there again. Not working as intended.
Boris doesn't see Chris' most recent mood, even after it's been accepted. Broken.

**Comment by VukR** [comment]
Fixed by henry
